### PR TITLE
null safety support

### PR DESCRIPTION
**Pull request by AhmedNourJamalElDin**

### CODE REVIEW

**Comment by realcr** [comment]
@AhmedNourJamalElDin: Thanks for your work on this PR!
It seems like Travis stopped working for this repository (It seems like I need to specifically request more credits), so I can not see automated tests results for your changes. Have you run ./tool/presubmit and the tests passed?

Aside from that, please tell me when you think that this code is ready to merge.

**Comment by AhmedNourJamalElDin** [comment]
Hi
Yea, all the tests passed.

The generated files seem to be fine. However, I need some days to migrate my project to support null-safety and flutter v2.

I will get back to you when my project gets fully working so I can be 100% sure the changes are ready to be merged.

**Comment by AhmedNourJamalElDin** [comment]
Hello,

I think we can merge it now

**Comment by AhmedNourJamalElDin** [comment]
Hello again,
Can we merge it, please?

**Pull request merged**
